name: Build CAN Tool

on:
  push:
    branches:
      - feature/packaged-executable
  pull_request:
    branches:
      - feature/packaged-executable

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci
          # --- Rollup native binary fix START ---
          # Context: npm sometimes fails to install optional OS-specific Rollup
          # binaries on Windows/macOS when using `npm ci`, which breaks Vite's build
          # with: `Cannot find module @rollup/rollup-<platform>`.
          # Workaround: install the correct optional Rollup package *without* saving
          # it to package.json, but only on Windows or macOS runners.
          case "$RUNNER_OS" in
            Windows)
              npm i --no-save @rollup/rollup-win32-x64-msvc ;;
            macOS)
              npm i --no-save @rollup/rollup-darwin-arm64 || npm i --no-save @rollup/rollup-darwin-x64 ;;
            Linux)
              # Linux selects the correct binary already; nothing to do.
              ;;
          esac
          # --- Rollup native binary fix END ---
          npm run build

      - name: Prepare static assets
        run: |
          rm -rf backend/static
          mkdir -p backend/static
          cp -r frontend/dist/* backend/static/

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build executable
        run: |
          pyinstaller --onefile \
            --name can-tool \
            --add-data "backend/static:static" \
            --add-data "backend/presets.json:." \
            --add-data "backend/groups.json:." \
            --paths backend \
            backend/__main__.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: can-tool-${{ matrix.os }}
          path: dist/can-tool*
