name: Build CAN Tool

on:
  push:        # still runs on every push
    branches: ["**"]
  workflow_dispatch:

jobs:
  build:
    name: build (${{ matrix.os }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: npm ci (frontend)
        working-directory: frontend
        run: npm ci

      # *** Same fix as in build.yml ***
      - name: Install Rollup native binary on Windows/macOS
        if: runner.os != 'Linux'
        shell: bash
        working-directory: frontend
        run: |
          if [[ "${RUNNER_OS}" == "Windows" ]]; then
            npm i --no-save @rollup/rollup-win32-x64-msvc
          elif [[ "${RUNNER_OS}" == "macOS" ]]; then
            npm i --no-save @rollup/rollup-darwin-arm64
          fi

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Stage frontend assets into backend/static
        shell: bash
        run: |
          mkdir -p backend/static
          cp -r frontend/dist/* backend/static/

      - name: Package app with PyInstaller
        run: pyinstaller can-tool.spec

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: can-tool-${{ matrix.os }}-${{ github.sha }}
          path: dist/*
          if-no-files-found: error
